Tonal Support
5hwb/Old-Hangul-Input-Method pull request #5
Opened 2022-02-24 04:29 UTC by DarpMosh

I've created Tonal Support.

2022-02-24 07:03 UTC, 5hwb requested changes

2022-02-24 07:03 UTC, 5hwb commented on README.md
> -Currently, Old Hangul Input Method supports typing characters in the 'Hangul Jamo' Unicode block. The archaic Hangul tone marks, 'Hangul Jamo Extended-A' and 'Hangul Jamo Extended-B' characters are c
Since 'Hangul Jamo Extended-A' and 'Hangul Jamo Extended-B' characters are still unsupported, this line shouldn't be deleted entirely.

2022-02-24 07:03 UTC, 5hwb commented on hangulime_new.js
> +var jamo_init_high    = new Jamo(jamo_nil, "F", JAMO_INITIAL, '〮', undefined);
I think that the tone marks should be given their own category 'TONE_MARK' instead of 'JAMO_INITIAL', but this can be fixed later

2022-02-24 19:17 UTC, DarpMosh commented on hangulime_new.js
> +var jamo_init_high    = new Jamo(jamo_nil, "F", JAMO_INITIAL, '〮', undefined);
Also, please don't forget to update the Keyboard. Thank you.

2022-02-25 00:23 UTC, 5hwb commented on README.md
> -Currently, Old Hangul Input Method supports typing characters in the 'Hangul Jamo' Unicode block. The archaic Hangul tone marks, 'Hangul Jamo Extended-A' and 'Hangul Jamo Extended-B' characters are c
I re-inserted the line. When modifying READMEs, please read carefully before removing a line of text.

2022-02-25 00:24 UTC, DarpMosh commented on README.md
> -Currently, Old Hangul Input Method supports typing characters in the 'Hangul Jamo' Unicode block. The archaic Hangul tone marks, 'Hangul Jamo Extended-A' and 'Hangul Jamo Extended-B' characters are c
Oh ok. I didn't know that I changed it. Perhaps this was an old version I was using?

2022-02-25 00:28 UTC, 5hwb commented on README.md
> -Currently, Old Hangul Input Method supports typing characters in the 'Hangul Jamo' Unicode block. The archaic Hangul tone marks, 'Hangul Jamo Extended-A' and 'Hangul Jamo Extended-B' characters are c
Yeah probably, I added the line fairly recently. It's all fixed now.

2022-02-25 00:28 UTC, 5hwb approved these changes
LGTM

2022-02-25 00:30 UTC, merged